service: qwik-city-e2e
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  memorySize: 128
  timeout: 10
  stage: dev
  environment:
    PLATFORM_NAME: aws

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 4000

package:
  excludeDevDependencies: true
  patterns:
    - './!**'
    - 'server/**'
    - 'dist/**'

plugins:
  - serverless-offline
