name: Azure SWA Server

on:
  push:

jobs:
  test:
    name: Test Azure Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Azure
        run: npm run build.azure

      - name: Print dist Build
        run: tree dist

      - name: Print server Build
        run: tree azure-functions

      - name: Deploy to Azure SWA
        run: npm run deploy.azure
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_DEPLOYMENT_TOKEN }}

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Test Azure Server MPA
        run: npm run test.azure.mpa

      - name: Test Azure Server SPA
        run: npm run test.azure.spa
