name: Azure SWA Server

on:
  push:
  repository_dispatch:
    types: [main-updated]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    name: Test Azure ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm Dependencies
        run: pnpm install && pnpm upgrade "@builder.io/qwik" "@builder.io/qwik-city"

      - name: Build Azure
        run: pnpm run build.azure

      # - name: Run
      #   run: pnpm run serve.azure

      # - name: Install Playwright
      #   run: npx playwright install chromium --with-deps

      # - name: Test Azure Server MPA
      #   run: pnpm run test.azure.mpa

      # - name: Test Azure Server SPA
      #   run: pnpm run test.azure.spa
