name: Create Qwik CLI

on:
  push:
  repository_dispatch:
    types: [main-updated]

jobs:
  test:
    name: Test Create Qwik CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm Dependencies
        run: pnpm install && pnpm upgrade @builder.io/qwik @builder.io/qwik-city

      - name: Run Create Qwik CLI
        run: node ./tests/cli.js
