name: Cloudflare Pages Server

on:
  push:
  repository_dispatch:
    types: [main-updated]

jobs:
  test:
    name: Test Cloudflare Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Cloudflare
        run: npm run build.cloudflare

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: qwik-city-e2e
          directory: dist

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Test Cloudflare Server MPA
        run: npm run test.cloudflare.mpa

      - name: Test Cloudflare Server SPA
        run: npm run test.cloudflare.spa
