name: Deno Server

on:
  push:
  repository_dispatch:
    types: [main-updated]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    name: Test Deno Servers ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install pnpm Dependencies
        run: pnpm install

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Build Deno Server
        run: pnpm run build.deno

      - name: Test Deno Server MPA
        run: pnpm run test.deno.mpa

      - name: Test Deno Server SPA
        run: pnpm run test.deno.spa
