name: E2E Tests

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install NPM Dependencies
        run: npm install ci

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Build Client
        run: npm run build.client

      - name: Build Server
        run: npm run build.express

      - name: Test
        run: npm run test.express
