name: Netlify Server

on:
  push:
  repository_dispatch:
    types: [main-updated]

jobs:
  test:
    name: Test Netlify Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm Dependencies
        run: pnpm install && pnpm upgrade @builder.io/qwik @builder.io/qwik-city

      - name: Deploy to Netlify
        run: pnpm run deploy.netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Test Netlify Server MPA
        run: pnpm run test.netlify.mpa

      - name: Test Netlify Server SPA
        run: pnpm run test.netlify.spa
