name: Node Servers

on:
  push:

jobs:
  test:
    name: Test Node Servers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Dependencies
        run: npm install

      # - name: Install Playwright
      #   run: npx playwright install chromium --with-deps

      # - name: Test Dev Server MPA
      #   run: npm run test.dev.mpa

      # - name: Test Dev Server SPA
      #   run: npm run test.dev.spa

      # - name: Build Vite Preview Server
      #   run: npm run build.preview

      # - name: Test Vite Preview Server MPA
      #   run: npm run test.preview.mpa

      # - name: Test Vite Preview Server SPA
      #   run: npm run test.preview.spa

      # - name: Clear dist dir
      #   run: rm -rf dist

      # - name: Build Express Server
      #   run: npm run build.express

      # - name: Test Express Server MPA
      #   run: npm run test.express.mpa

      # - name: Test Express Server SPA
      #   run: npm run test.express.spa

      # - name: Clear dist dir
      #   run: rm -rf dist

      - name: Build Static Server
        run: npm run build.static

      - name: Test Static Server MPA
        run: npm run test.static.mpa

      - name: Test Static Server SPA
        run: npm run test.static.spa
