name: Node Servers

on:
  push:
  repository_dispatch:
    types: [main-updated]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    name: Test Node Servers ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm Dependencies
        run: pnpm install && pnpm upgrade @builder.io/qwik @builder.io/qwik-city

      - name: Run Vitest
        run: pnpm run test.unit

      - name: Run TypeChecker
        run: pnpm run build.types

      - name: Run Linter
        run: pnpm run lint

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Test Dev Server MPA
        run: pnpm run test.dev.mpa

      - name: Test Dev Server SPA
        run: pnpm run test.dev.spa

      - name: Build Vite Preview Server
        run: pnpm run build.preview

      - name: Test Vite Preview Server MPA
        run: pnpm run test.preview.mpa

      - name: Test Vite Preview Server SPA
        run: pnpm run test.preview.spa

      - name: Clear dist dir
        run: pnpm run clean.dist

      - name: Build Express Server
        run: pnpm run build.express

      - name: Test Express Server MPA
        run: pnpm run test.express.mpa

      - name: Test Express Server SPA
        run: pnpm run test.express.spa

      - name: Clear dist dir
        run: pnpm run clean.dist

      - name: Build Node Server
        run: pnpm run build.node

      - name: Test Node Server MPA
        run: pnpm run test.node.mpa

      - name: Test Node Server SPA
        run: pnpm run test.node.spa

      - name: Clear dist dir
        run: pnpm run clean.dist

      - name: Build Node Server (development)
        run: pnpm run build.node-dev

      - name: Test Node Server (development) MPA
        run: pnpm run test.node-dev.mpa

      - name: Test Node Server (development) SPA
        run: pnpm run test.node-dev.spa

      - name: Clear dist dir
        run: pnpm run clean.dist

      - name: Build Static Server
        run: pnpm run build.static

      - name: Test Static Server MPA
        run: pnpm run test.static.mpa

      - name: Test Static Server SPA
        run: pnpm run test.static.spa
