name: Node Servers

on:
  push:

jobs:
  test:
    name: Test Node Servers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Dependencies
        run: npm install i

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Test Dev Server
        run: npm run test.dev

      - name: Build Client for all Servers
        run: npm run build.client

      - name: Build Vite Preview Server
        run: npm run build.preview

      - name: Test Vite Preview Server
        run: npm run test.preview

      - name: Build Express Server
        run: npm run build.express

      - name: Test Express Server
        run: npm run test.express
