name: Vercel

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install NPM Dependencies
        run: npm install ci

      - name: Deploy
        run: npm run deploy.vercel -- --token=${{ secrets.VERCEL_QWIK_CITY_E2E_TOKEN }}

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Test
        run: npm run test.vercel
