name: Vercel Server

on:
  push:

jobs:
  test:
    name: Test Vercel Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install NPM Dependencies
        run: pnpm install

      - name: Deploy to Vercel
        run: pnpm run deploy.vercel -- --token=${{ secrets.VERCEL_QWIK_CITY_E2E_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Test Vercel Server MPA
        run: npm run test.vercel.mpa

      - name: Test Vercel Server SPA
        run: npm run test.vercel.spa
